---
- name: Add gpg key of hashicorp
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    mode: '0644'
  when: ansible_distribution == 'Ubuntu' or
    ansible_distribution == 'Debian'

- name: Add apt repository for packer
  ansible.builtin.apt_repository:
    repo: deb https://apt.releases.hashicorp.com bionic main
    state: present
  when: ansible_distribution == 'Ubuntu' and
        ansible_distribution_release == 'bionic'

- name: Add apt repository for packer
  ansible.builtin.apt_repository:
    repo: deb https://apt.releases.hashicorp.com focal main
    state: present
  when: ansible_distribution == 'Ubuntu' and
        ansible_distribution_release == 'focal'

- name: Add apt repository for packer
  ansible.builtin.apt_repository:
    repo: deb https://apt.releases.hashicorp.com jammy main
    state: present
  when: ansible_distribution == 'Ubuntu' and
        ansible_distribution_release == 'jammy'

- name: Add apt repository for packer
  ansible.builtin.apt_repository:
    repo: deb https://apt.releases.hashicorp.com noble main
    state: present
  when: ansible_distribution == 'Ubuntu' and
        ansible_distribution_release == 'noble'

- name: Add apt repository for packer
  ansible.builtin.apt_repository:
    repo: deb https://apt.releases.hashicorp.com plucky main
    state: present
  when: ansible_distribution == 'Ubuntu' and
        ansible_distribution_release == 'plucky'

- name: Add apt repository for packer
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com bookworm main"
    state: present
    filename: hashicorp
  when: ansible_distribution == 'Debian' and (
        ansible_distribution_release == 'bookworm' or
        ansible_distribution_release == 'trixie' )

- name: install packer in Ubuntu
  apt:
    name: ['packer']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu" or
    ansible_distribution == 'Debian'
