---
- name: Add gpg key of hashicorp
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    mode: '0644'
  when: ansible_distribution == 'Ubuntu'
     or ansible_distribution == 'Debian'

- name: Add apt repository for packer
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ arch }} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ release }} main"
    state: present
  when: ansible_distribution == 'Ubuntu'
     or ansible_distribution == 'Debian'

- name: install packer in Ubuntu
  apt:
    name: ['packer']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
     or ansible_distribution == 'Debian'
