---
- name: Add gpg key of hashicorp
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/trusted.gpg.d/hashicorp-archive-keyring.asc
  when: ansible_distribution == 'Ubuntu'
     or ansible_distribution == 'Debian'

- name: Add apt repository for packer
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ arch }} signed-by=/etc/apt/trusted.gpg.d/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ release }} main"
    state: present
    filename: hashicorp
  when: ansible_distribution == 'Ubuntu'
     or ansible_distribution == 'Debian'

- name: install packer in Ubuntu
  apt:
    name: ['packer']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
     or ansible_distribution == 'Debian'
